-- 1. Add 'type' column to Trackers (Wallet or Allowance)
alter table trackers add column if not exists type text default 'wallet';

-- 2. Add 'category' if you missed it last time
alter table transactions add column if not exists category text;

-- 3. Create Archives (if missing)
create table if not exists archives (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_pin text not null,
  tracker_name text not null,
  final_balance numeric not null
);